---
functional:
  - Пользователь имеет возможность подключиться к случайной игре с ботом без регистрации
  - Пользователь имеет возможность зарегистрироваться на сайте с помошью e-mail
  - Пользователь имеет возможность авторизоваться на сайте с помощью Github
  - Пользователь имеет возможность авторизоваться на сайте с помощью Discord
  - Пользователь имеет возможность авторизоваться на сайте с помощью e-mail и пароля
  - Пользователь имеет возможность восстановить забытый пароль
  - Имя пользователя должно состоять из латинских букв, содержать цифры, нижние подчеркивания и начинаться с заглавной буквы
  - Имя пользователя должно содержать от 3 до 16 символов
  - Пароль должен содержать от 6 до 16 символов
  - E-mail должен быть валидным
  - Пользователь может оставлять сообщения в чате General
  - Пользователь может создать новую игру, задав уровень сложности
  - Пользователь может создать новую игру с другим пользователем, с другом, с ботом
  - Пользователь может создать новую игру, задав время в диапазоне от 3 до 60 минут
  - Пользователь может при создании игры выбрать задачу по названию или по тегам
  - Пользователь может присоединиться к созданной другим пользователем игре
  - Пользователь имеет возможность создать турнир
  - Пользователь может просматривать созданные другими пользователями турниры
  - Пользователь имеет возможность участвовать в активных турнирах других пользователей
  - Пользователь может фильтровать рейтинг игроков по имении пользователя
  - Пользователь может фильтровать рейтинг игроков по игре с ботом
  - Пользователь может сортировать рейтинг игроков по критериям 
  - Пользователь может фильтровать рейтинг игроков по временному промежутку
  - Пользователь имеет возможность завершить игру, выполнив задание
  - Пользователь имеет возможность завершить игру по времени
  - Пользователь имеет возможность сдаться во время игры
  - Пользователь имеет возможность просматривать завершенные игры
  - Пользователь получает очки за игры, что отображается в рейтинге
  - Пользователь может отправить сообщение во время игры
  - В игре имеется возможность выбрать язык программирования
  - Пользователь продолжает игру по времени, несмотря на отсутствие соперника
  - Пользователь, которого выкинуло, может продолжить игру, если ее время не окончено
  - Задача предлагается на русском и английском языках
  - Пользователь имеет возможность развернуть задачу в отдельное модальное окно
  - Пользователь может просмотреть гайд к игре
  - Пользователь может просматривать списки игр и подключаться к доступным для подключения играм, созданными другими игроками
  - Пользователь имеет возможность перехода в vim-режим
  - Пользователь имеет возможность просматривать процесс написания кода соперником в режиме online
  - Пользователь имеет возможность проверить своё решение неограниченное количество раз
  - Пользователь имеет возможность получить уведомление о приглашении на игру
  - Пользователь имеет возможность просмотреть и скопировать ссылку созданной им игры
  - Пользователь имеет возможность выйти из игры на основную страницу
  - Пользователь имеет возможность сбросить свое решение задачи
  - Пользователь имеет возможность поменять цветовую тему терминала
  - Пользователь имеет возможность взять реванш в случае проигрыша
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Запрет на копирование кода в окне редактора
  - Пользователь может остаться в игре после определения победителя (или окончания установленного лимита на таймере) и дописать код / ознакомиться с кодом
  - Пользователь не может писать и изменять код соперника
  - Зрители не могут писать код и вносить изменения в код участников игры
  - Зрители не могут оставлять комментарии в чат участников игры
  - Пользователи не могут вносить изменения в таблицу лидеров вручную
  - Участники не могут изменять задания
  - На сайте должен быть способ оставления обратной связи в случае нахождения бага или предложения возможности для улучшения
