---
functional:
  - Пользователь имеет возможность подключиться к случайной игре с ботом без регистрации
  - Пользователь имеет возможность зарегистрироваться на сайте с помошью e-mail
  - Пользователь имеет возможность авторизоваться на сайте с помошью Github
  - Пользователь имеет возможность авторизоваться на сайте с помошью Discord
  - Пользователь имеет возможность авторизоватьсч на сайте с помощью e-mail и пароля
  - Пользователь имеет возможность восстановить забытый пароль
  - Имя пользователя должно состоять из латинских букв, содержать цифры, нижние подчеркивания и начинаться с заглавной буквы
  - Имя пользователя должно содержать от 3 до 16 символов
  - Пароль должен содержать от 6 до 16 символов
  - E-mail должен быть валидным
  - 
non-functional:
  - 
  - 
implicit:
  - 
  - 
